# Generated by Django 4.0.2 on 2022-02-25 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_photo_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='name',
            new_name='image',
        ),
    ]
